### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by varlesh**

### CODE REVIEW

**Comment by rockon999** [comment]
Hi! I'm still adding features for the next release and working out any kinks that may mess up the extension. I'll merge your translations when I'm ready to release the next version! :)

**Comment by varlesh** [comment]
ok ) Close if you need

**Comment by rockon999** [comment]
Could you update your branch and translate 'Add Text Shadows' from the newest version. Thanks!

**Comment by varlesh** [comment]
ok pull #19

**Pull request closed without merging**
