### PR TITLE
Updated German translation

### PR DESCRIPTION
**Pull request by jonnius**
By the way: The String "default" is still shown in English. I could not find the reason...

### CODE REVIEW

**Comment by rockon999** [comment]
I'll look into it. Thanks!

**Comment by rockon999** [comment]
Bug fixed. Entire interface should now be in German!

**Comment by rockon999** [comment]
I had to change the instructions for WM_CLASS from 'first results' to 'second results'. I think I updated the German correctly but if you could glance at it I'd be very grateful!

**Comment by jonnius** [comment]
It is correct! :+1:

**Pull request merged**
