### PR TITLE
Dynamic Panel Transparency in pt_BR

### PR DESCRIPTION
**Pull request by frnogueira**
;)

### CODE REVIEW

**Comment by rockon999** [comment]
Hi! I'm currently adding features for the next release and working out any bugs that may effect the end user. I'll merge your translations when I'm ready to release the next version! :)

**Comment by frnogueira** [comment]
OK! :+1:

**Comment by rockon999** [comment]
Could you update your branch and translate 'Add Text Shadows' from the newest version. Thanks!

**Comment by frnogueira** [comment]
Updated! ;)

**Comment by rockon999** [comment]
Hi! v11 of Dynamic Panel Transparency is in the master branch! Many new features have arrived such as customizable text & icon shadows, app settings, and transition styles! With these new features, many new strings have been added. If you are still willing to help translate the new version into Brazilian Portuguese I'd very much appreciate it! I completely understand, however, if you cannot do so at this time.

In v11, I've added you as a translator in the extension credits.

If you come across any bugs feel free to let me know! v11 was a major rewrite.

**Comment by frnogueira** [comment]
That's ok... I'll see right now.. ;)

**Pull request merged**
